name: findrobe_app
description: "University Assignment"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.8
  crypto: ^3.0.5
  curved_navigation_bar: ^1.0.6
  collection: ^1.18.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_local_notifications: ^17.2.3
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  multi_image_picker_view: ^1.1.0
  shared_preferences: ^2.3.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_native_splash:
  android: true
  color: "#3B3B3B"
  image: "assets/logo.png"
  
  android_12:
    color: "#3B3B3B"
    image: "assets/logo.png"