// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZa_Ic1mlXNTnRKRYRNqDjOXOCzXvK3CQ',
    appId: '1:793288458753:web:e4f1954ceb0c37bcd3f600',
    messagingSenderId: '793288458753',
    projectId: 'euge-babd2',
    authDomain: 'euge-babd2.firebaseapp.com',
    storageBucket: 'euge-babd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHgcV8TpO1T7uemZJZLgB_UeqrrJSRAxU',
    appId: '1:793288458753:android:18b0f1198d3aaf26d3f600',
    messagingSenderId: '793288458753',
    projectId: 'euge-babd2',
    storageBucket: 'euge-babd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyewYVXqZTE8ELm3-XrTSFwq732byMwCs',
    appId: '1:793288458753:ios:682ecbbc1b40529bd3f600',
    messagingSenderId: '793288458753',
    projectId: 'euge-babd2',
    storageBucket: 'euge-babd2.appspot.com',
    iosBundleId: 'com.example.findrobeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyewYVXqZTE8ELm3-XrTSFwq732byMwCs',
    appId: '1:793288458753:ios:682ecbbc1b40529bd3f600',
    messagingSenderId: '793288458753',
    projectId: 'euge-babd2',
    storageBucket: 'euge-babd2.appspot.com',
    iosBundleId: 'com.example.findrobeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZa_Ic1mlXNTnRKRYRNqDjOXOCzXvK3CQ',
    appId: '1:793288458753:web:4f7825382028fc9cd3f600',
    messagingSenderId: '793288458753',
    projectId: 'euge-babd2',
    authDomain: 'euge-babd2.firebaseapp.com',
    storageBucket: 'euge-babd2.appspot.com',
  );
}
